### ISSUE TITLE
Convert to python 3

### ISSUE THREAD

**Issue by johnnykv** [johnnykv/heralding#15]

**Comment by czardoz** [comment]
Will require forking of https://github.com/ianepperson/telnetsrvlib

It has a few print statements, etc.

**Comment by johnnykv** [comment]
Maybe we can convince @ianepperson to go python 3 with telnetsrvlib :-)

**Comment by czardoz** [comment]
I actually got it touch with him a few months ago, but it didn't really go anywhere :-(

I've forked the library [here](https://github.com/czardoz/libtelnetsrv), but it needs a lot more work to make it usable. I got things to run, but there are some issues with the whole `string` vs `bytes` thing.

I do plan to maintain it in the long term, so I'll update this issue when the fork is usable.

**Comment by johnnykv** [comment]
Feel free to give it a shot :-) Maybe we could strip down telnetsrvlib to only provide the support needed? At least for the Heralding project, nothing of the interactive command stuff is needed.

**Comment by czardoz** [comment]
I need that for one of my projects, so I'll let that be. I've removed support for eventlet though.

**Comment by johnnykv** [comment]
Okay, sound good. Did you already try 2to3 on in?

**Comment by czardoz** [comment]
I did, but it didn't really help. The only change it handled was converting `SocketServer` to `socketserver` :stuck_out_tongue:

**Comment by johnnykv** [comment]
Ok, I am pretty far in converting the heralding project to py3 (excluding the parts that uses telnetsrvlib).

**Comment by czardoz** [comment]
I can see! 

I need to get the escape sequences to work, the rest of the funcctionality seems to be working :+1:

**Comment by glaslos** [comment]
Did you consider replacing gevent with asyncio?

**Comment by mohanagr** [comment]
I have been recently introduced to Heralding and am looking to contribute to this whole porting to Python3 thing. How can I get started?

**Comment by johnnykv** [comment]
I would suggest that you for starters familiarize yourself with heralding in general (functionality, architecture, etc). After that I would suggest 2to3 tool on heralding and start fixing stuff that is broken after 2to3 :-)

Note that the dependency on telnetsrvlib might be an issue, so could gevent...

**Comment by mohanagr** [comment]
Although I have read a bit about it, I do not have any experience in asyncio. I am experienced with python multithreading and zeromq for that matter. I have been trying to get my hands on #21 to no avail yet.

**Comment by czardoz** [comment]
Mohan,

I think you should first reproduce the issue. Trying to do that will ensure
that you:

1. Are able to set up heralding for development
2. Are able to run existing unit tests
3. Gain familiarity with the "edit -> run code -> test changes -> edit
again" loop

On 01-Mar-2017 2:21 AM, "Mohan Agrawal" <notifications@github.com> wrote:

Although I have read a bit about it, I do not have any experience in
asyncio. I am experienced with python multithreading and zeromq for that
matter. I have been trying to get my hands on #21
<https://github.com/johnnykv/heralding/issues/21> to no avail yet.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/johnnykv/heralding/issues/15#issuecomment-283156615>,
or mute the thread

**Comment by mohanagr** [comment]
Reproducing the issue was simple enough by sending random data to port I specify in ssh capability. All the tests are passing too. I will be going through the working and 2to3 on core files.
