### ISSUE TITLE
Logging of auxiliary data

### ISSUE THREAD

**Issue by johnnykv** [johnnykv/heralding#91]
Each capability potentially allows for logging of auxiliary data, for example user_agent (HTTP) and client version (SSH). Heralding need to log this data somehow.

Each protocol could log it's own aux data in a separate log file (aux_ssh.log) or it could be a global XML aux log file. Whatever the log format, it should be machine readable (xml, csv, json, etc).

Inspired by issue #85.

**Comment by realsdx** [comment]
I want to work on this issue. Is HTTP , and ssh are currently being targeted for logging auxiliary data ?

**Comment by kajojify** [comment]
@realsdx Hi! :) 
Thank you for paying attention to this.
As Johnny said:
> Each capability potentially allows for logging of auxiliary data...
Not only HTTP and SSH are targeted. They are just examples. We have to consider each capability and try to find auxiliary data to log.
If you want to work on this, please coordinate with Devesh Chande, since he also started to work on this https://github.com/johnnykv/heralding/issues/85#issuecomment-462012137
Currently he works on HTTP, so you can take SSH or any other protocol. Please, contact him concerning details.

**Comment by realsdx** [comment]
Okay, thanks. I will start working on SSH then.
